version: "3"

services:
  ibmmq:
    build: .
    container_name: booklibapp-ibmmq
    ports:
      - "1414:1414" # Port for application
      - "9443:9443" # Port for web console
    volumes:
      - "./.data/mq:/mnt/mqm"
# type `docker-compose up -d` in command line to run container
