CREATE TABLE BOOK (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
	
	PRIMARY KEY(ID)
);

CREATE TABLE AUTHOR (
	ID INT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(40) NOT NULL,
	LAST_NAME VARCHAR(40) NOT NULL,
	
	PRIMARY KEY(ID)
);

CREATE TABLE BOOK_AUTHOR (
	BOOK_ID INT NOT NULL,
	AUTHOR_ID INT NOT NULL,
	
	PRIMARY KEY(BOOK_ID, AUTHOR_ID),
	CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID),
	CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);